### ISSUE TITLE
This is how it supposed to work, or i'm doing something wrong?

### ISSUE THREAD

**Issue by ZeroCool22** [ahrm/UnstableFusion#14]
https://user-images.githubusercontent.com/13344308/192045351-f776f19b-a4b8-4d9d-aef3-2e96c6f61a10.mp4

**Comment by ahrm** [comment]
So the reason is pretty hard to explain, but it is a limitation of the initializer algorithm, and the fact that the area surrounding your subject has to be white (because we are not allowed to change the non-backgroud pixels). So the model has to somehow incorporate this white color into the image which is pretty difficult.

You can use paint/photoshop to convert that white color to a color matching the brown background and you will probably get a much better result.

**Comment by ZeroCool22** [comment]
> So the reason is pretty hard to explain, but it is a limitation of the initializer algorithm, and the fact that the area surrounding your subject has to be white (because we are not allowed to change the non-backgroud pixels). So the model has to somehow incorporate this white color into the image which is pretty difficult.
> 
> You can use paint/photoshop to convert that white color to a color matching the brown background and you will probably get a much better result.

I understand, thx.
