### ISSUE TITLE
512x512 limite?

### ISSUE THREAD

**Issue by roozbehid** [ahrm/UnstableFusion#28]
I think I saw in several repos there is some initial restriction on size and some repos that remove it?
Is there such a limit and if so why is it there?Is it possible to easily remove it?

Overall I want my width height to be increased more.

**Comment by ahrm** [comment]
It is possible to use stable diffusion with other resolutions. However, since it was trained on 512*512 images, the quality of the results is very bad. So I don't think it is worth it to include this option.

You can always increase the image size using the increase/decrease image size buttons. There is also a check box which disables the box size limit, but it just upscales the 512*512 results so it is not sharp.
